builds:
  - binary: mubeng
    main: cmd/mubeng/main.go
    ldflags:
      - -s -w -X ktbs.dev/mubeng/common.Version=v{{.Version}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
  
archives:
  - id: binary
    format: binary
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64